## spring security é…ç½®
security:
  oauth2:
    client:
      ignore-urls:
        - /**
spring:
  cache:
    type: redis
  data:
    redis:
      host: 14.103.193.249
      port: 6379
      password: wakeyoga123
      database: 1
  # æ•°æ®åº“ç›¸å…³é…ç½®
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: c45540d049692a9c
      url: jdbc:mysql://14.103.193.249:3306/databridge?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true

# =========================
# ğŸ· PigX é…ç½®
# =========================
pigx:
  mybatis:
    show-sql: true