spring:
  datasource:
    url: jdbc:mysql://localhost:3306/databridge?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.pig4cloud.databridge: INFO
